services:
  - type: web
    name: votacao-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        scope: build
      - key: SUPABASE_KEY
        scope: build
      - key: JWT_SECRET
        scope: build
      - key: PORT
        value: 3000
